/* Generated by Yosys 0.20+45 (git sha1 029c2785e, clang 13.0.1 -fPIC -Os) */

(* top =  1  *)
(* src = "counter_4_bits.v:90.1-185.10" *)
module counter_16_bits(Q, w1, w2, w3, w4, D, CLK, ENB, MODO);
  (* src = "counter_4_bits.v:92.11-92.14" *)
  wire _00_;
  (* src = "counter_4_bits.v:93.17-93.21" *)
  wire _01_;
  (* src = "counter_4_bits.v:93.17-93.21" *)
  wire _02_;
  (* src = "counter_4_bits.v:101.9-101.11" *)
  wire _03_;
  (* src = "counter_4_bits.v:101.13-101.15" *)
  wire _04_;
  (* src = "counter_4_bits.v:101.17-101.19" *)
  wire _05_;
  (* src = "counter_4_bits.v:101.21-101.23" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "counter_4_bits.v:105.10-105.14" *)
  wire _11_;
  (* src = "counter_4_bits.v:105.16-105.20" *)
  wire _12_;
  (* src = "counter_4_bits.v:105.22-105.26" *)
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "counter_4_bits.v:96.12-96.14" *)
  wire _25_;
  (* src = "counter_4_bits.v:96.15-96.17" *)
  wire _26_;
  (* src = "counter_4_bits.v:96.19-96.21" *)
  wire _27_;
  (* src = "counter_4_bits.v:96.22-96.24" *)
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  (* src = "counter_4_bits.v:138.13-138.20" *)
  wire _44_;
  (* src = "counter_4_bits.v:138.24-138.31" *)
  wire _45_;
  (* src = "counter_4_bits.v:138.35-138.42" *)
  wire _46_;
  (* src = "counter_4_bits.v:172.19-172.33" *)
  wire _47_;
  (* src = "counter_4_bits.v:172.37-172.51" *)
  wire _48_;
  (* src = "counter_4_bits.v:173.37-173.51" *)
  wire _49_;
  (* src = "counter_4_bits.v:174.37-174.51" *)
  wire _50_;
  (* src = "counter_4_bits.v:138.13-138.31" *)
  wire _51_;
  (* src = "counter_4_bits.v:138.13-138.42" *)
  wire _52_;
  (* src = "counter_4_bits.v:92.11-92.14" *)
  input CLK;
  wire CLK;
  (* src = "counter_4_bits.v:91.18-91.19" *)
  input [15:0] D;
  wire [15:0] D;
  (* src = "counter_4_bits.v:94.11-94.14" *)
  input ENB;
  wire ENB;
  (* src = "counter_4_bits.v:93.17-93.21" *)
  input [1:0] MODO;
  wire [1:0] MODO;
  (* src = "counter_4_bits.v:95.19-95.20" *)
  output [15:0] Q;
  wire [15:0] Q;
  (* init = 1'h0 *)
  (* src = "counter_4_bits.v:101.9-101.11" *)
  wire a1;
  (* init = 1'h0 *)
  (* src = "counter_4_bits.v:101.13-101.15" *)
  wire a2;
  (* init = 1'h0 *)
  (* src = "counter_4_bits.v:101.17-101.19" *)
  wire a3;
  (* src = "counter_4_bits.v:101.21-101.23" *)
  wire a4;
  (* src = "counter_4_bits.v:105.10-105.14" *)
  wire clk1;
  (* src = "counter_4_bits.v:105.16-105.20" *)
  wire clk2;
  (* src = "counter_4_bits.v:105.22-105.26" *)
  wire clk3;
  (* src = "counter_4_bits.v:104.10-104.17" *)
  wire modo_11;
  (* src = "counter_4_bits.v:96.12-96.14" *)
  output w1;
  wire w1;
  (* src = "counter_4_bits.v:96.15-96.17" *)
  output w2;
  wire w2;
  (* src = "counter_4_bits.v:96.19-96.21" *)
  output w3;
  wire w3;
  (* src = "counter_4_bits.v:96.22-96.24" *)
  output w4;
  wire w4;
  NOT _53_ (
    .A(_28_),
    .Y(_14_)
  );
  NAND _54_ (
    .A(_01_),
    .B(_02_),
    .Y(_15_)
  );
  NOT _55_ (
    .A(_15_),
    .Y(_16_)
  );
  NAND _56_ (
    .A(_06_),
    .B(_15_),
    .Y(_17_)
  );
  NAND _57_ (
    .A(_14_),
    .B(_27_),
    .Y(_18_)
  );
  NAND _58_ (
    .A(_26_),
    .B(_25_),
    .Y(_19_)
  );
  NOR _59_ (
    .A(_18_),
    .B(_19_),
    .Y(_20_)
  );
  NAND _60_ (
    .A(_17_),
    .B(_20_),
    .Y(_07_)
  );
  NAND _61_ (
    .A(_00_),
    .B(_16_),
    .Y(_21_)
  );
  NAND _62_ (
    .A(_25_),
    .B(_15_),
    .Y(_22_)
  );
  NAND _63_ (
    .A(_21_),
    .B(_22_),
    .Y(_11_)
  );
  NAND _64_ (
    .A(_26_),
    .B(_15_),
    .Y(_23_)
  );
  NAND _65_ (
    .A(_21_),
    .B(_23_),
    .Y(_12_)
  );
  NAND _66_ (
    .A(_27_),
    .B(_15_),
    .Y(_24_)
  );
  NAND _67_ (
    .A(_21_),
    .B(_24_),
    .Y(_13_)
  );
  (* src = "counter_4_bits.v:125.5-168.8" *)
  DFF _68_ (
    .C(CLK),
    .D(_36_),
    .Q(a4)
  );
  (* src = "counter_4_bits.v:125.5-168.8" *)
  DFF _69_ (
    .C(CLK),
    .D(_38_),
    .Q(a1)
  );
  (* src = "counter_4_bits.v:125.5-168.8" *)
  DFF _70_ (
    .C(CLK),
    .D(_40_),
    .Q(a2)
  );
  (* src = "counter_4_bits.v:125.5-168.8" *)
  DFF _71_ (
    .C(CLK),
    .D(_42_),
    .Q(a3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_4_bits.v:181.20-181.100" *)
  counter_4_bits counter_FSB (
    .CLK(clk1),
    .D(D[7:4]),
    .ENB(a2),
    .MODO(MODO),
    .Q(Q[7:4]),
    .RCO(w2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_4_bits.v:180.20-180.99" *)
  counter_4_bits counter_LSB (
    .CLK(CLK),
    .D(D[3:0]),
    .ENB(a1),
    .MODO(MODO),
    .Q(Q[3:0]),
    .RCO(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_4_bits.v:183.20-183.104" *)
  counter_4_bits counter_MSB (
    .CLK(clk3),
    .D(D[15:12]),
    .ENB(a4),
    .MODO(MODO),
    .Q(Q[15:12]),
    .RCO(w4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter_4_bits.v:182.20-182.102" *)
  counter_4_bits counter_SSB (
    .CLK(clk2),
    .D(D[11:8]),
    .ENB(a3),
    .MODO(MODO),
    .Q(Q[11:8]),
    .RCO(w3)
  );
  assign _10_ = 1'h1;
  assign _09_ = 1'h1;
  assign _08_ = 1'h1;
  assign _05_ = a3;
  assign _04_ = a2;
  assign _03_ = a1;
  assign _06_ = a4;
  assign _36_ = _07_;
  assign _38_ = _08_;
  assign _40_ = _09_;
  assign _42_ = _10_;
  assign _01_ = MODO[0];
  assign _02_ = MODO[1];
  assign _28_ = w4;
  assign _27_ = w3;
  assign _26_ = w2;
  assign _25_ = w1;
  assign clk1 = _11_;
  assign clk2 = _12_;
  assign _00_ = CLK;
  assign clk3 = _13_;
endmodule

(* src = "counter_4_bits.v:12.1-84.10" *)
module counter_4_bits(Q, RCO, D, ENB, CLK, MODO);
  (* src = "counter_4_bits.v:24.17-24.18" *)
  wire _000_;
  (* src = "counter_4_bits.v:24.17-24.18" *)
  wire _001_;
  (* src = "counter_4_bits.v:24.17-24.18" *)
  wire _002_;
  (* src = "counter_4_bits.v:24.17-24.18" *)
  wire _003_;
  (* src = "counter_4_bits.v:26.11-26.14" *)
  wire _004_;
  (* src = "counter_4_bits.v:25.17-25.21" *)
  wire _005_;
  (* src = "counter_4_bits.v:25.17-25.21" *)
  wire _006_;
  (* src = "counter_4_bits.v:29.15-29.21" *)
  wire _007_;
  (* src = "counter_4_bits.v:29.15-29.21" *)
  wire _008_;
  (* src = "counter_4_bits.v:29.15-29.21" *)
  wire _009_;
  (* src = "counter_4_bits.v:29.15-29.21" *)
  wire _010_;
  (* src = "counter_4_bits.v:31.16-31.19" *)
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire [1:0] _097_;
  wire [1:0] _098_;
  wire [1:0] _099_;
  wire [1:0] _100_;
  wire [1:0] _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  (* src = "counter_4_bits.v:50.16-50.27" *)
  wire _107_;
  (* src = "counter_4_bits.v:53.20-53.37" *)
  wire _108_;
  (* src = "counter_4_bits.v:58.21-58.32" *)
  wire _109_;
  (* src = "counter_4_bits.v:65.21-65.34" *)
  wire _110_;
  (* src = "counter_4_bits.v:72.22-72.35" *)
  wire _111_;
  (* src = "counter_4_bits.v:61.20-61.37" *)
  wire _112_;
  (* src = "counter_4_bits.v:68.41-68.58" *)
  wire _113_;
  (* src = "counter_4_bits.v:68.62-68.79" *)
  wire _114_;
  (* src = "counter_4_bits.v:68.20-68.58" *)
  wire _115_;
  (* src = "counter_4_bits.v:68.20-68.79" *)
  wire _116_;
  wire _117_;
  wire _118_;
  wire [3:0] _119_;
  wire [3:0] _120_;
  wire [3:0] _121_;
  wire [3:0] _122_;
  wire _123_;
  wire _124_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:51.27-51.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [31:0] _125_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:51.27-51.37|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _126_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:51.27-51.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _127_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [3:0] _128_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _129_;
  wire _130_;
  wire _131_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:68.41-68.58|counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [3:0] _132_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:68.41-68.58|counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _133_;
  wire _134_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:68.62-68.79|counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [3:0] _135_;
  wire _136_;
  wire _137_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:59.27-59.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _138_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:67.27-67.37|counter_4_bits.v:59.27-59.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _139_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4_bits.v:67.27-67.37|counter_4_bits.v:59.27-59.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _140_;
  (* src = "counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _141_;
  (* src = "counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _142_;
  (* src = "counter_4_bits.v:68.41-68.58|counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _143_;
  (* src = "counter_4_bits.v:68.41-68.58|counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _144_;
  (* src = "counter_4_bits.v:68.62-68.79|counter_4_bits.v:68.20-68.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _145_;
  (* src = "counter_4_bits.v:67.27-67.37|counter_4_bits.v:59.27-59.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _146_;
  (* src = "counter_4_bits.v:27.11-27.14" *)
  input CLK;
  wire CLK;
  (* src = "counter_4_bits.v:24.17-24.18" *)
  input [3:0] D;
  wire [3:0] D;
  (* src = "counter_4_bits.v:26.11-26.14" *)
  input ENB;
  wire ENB;
  (* src = "counter_4_bits.v:25.17-25.21" *)
  input [1:0] MODO;
  wire [1:0] MODO;
  (* src = "counter_4_bits.v:28.18-28.19" *)
  output [3:0] Q;
  wire [3:0] Q;
  (* src = "counter_4_bits.v:29.15-29.21" *)
  wire [3:0] Q_temp;
  (* src = "counter_4_bits.v:31.16-31.19" *)
  output RCO;
  wire RCO;
  NOT _147_ (
    .A(_010_),
    .Y(_017_)
  );
  NOT _148_ (
    .A(_009_),
    .Y(_018_)
  );
  NOT _149_ (
    .A(_008_),
    .Y(_019_)
  );
  NOT _150_ (
    .A(_007_),
    .Y(_020_)
  );
  NOT _151_ (
    .A(_004_),
    .Y(_021_)
  );
  NOT _152_ (
    .A(_006_),
    .Y(_022_)
  );
  NOT _153_ (
    .A(_005_),
    .Y(_023_)
  );
  NOT _154_ (
    .A(_000_),
    .Y(_024_)
  );
  NOT _155_ (
    .A(_002_),
    .Y(_025_)
  );
  NOR _156_ (
    .A(_022_),
    .B(_023_),
    .Y(_026_)
  );
  NAND _157_ (
    .A(_006_),
    .B(_005_),
    .Y(_027_)
  );
  NOR _158_ (
    .A(_024_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _159_ (
    .A(_007_),
    .B(_026_),
    .Y(_029_)
  );
  NOR _160_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _161_ (
    .A(_021_),
    .B(_030_),
    .Y(_012_)
  );
  NAND _162_ (
    .A(_008_),
    .B(_007_),
    .Y(_031_)
  );
  NOT _163_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _164_ (
    .A(_008_),
    .B(_007_),
    .Y(_033_)
  );
  NAND _165_ (
    .A(_019_),
    .B(_020_),
    .Y(_034_)
  );
  NAND _166_ (
    .A(_031_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _167_ (
    .A(_005_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _168_ (
    .A(_006_),
    .B(_023_),
    .Y(_037_)
  );
  NAND _169_ (
    .A(_022_),
    .B(_005_),
    .Y(_038_)
  );
  NAND _170_ (
    .A(_035_),
    .B(_037_),
    .Y(_039_)
  );
  NAND _171_ (
    .A(_001_),
    .B(_026_),
    .Y(_040_)
  );
  NAND _172_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _173_ (
    .A(_036_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _174_ (
    .A(_021_),
    .B(_042_),
    .Y(_013_)
  );
  NOR _175_ (
    .A(_018_),
    .B(_031_),
    .Y(_043_)
  );
  NOT _176_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _177_ (
    .A(_009_),
    .B(_032_),
    .Y(_045_)
  );
  NAND _178_ (
    .A(_018_),
    .B(_031_),
    .Y(_046_)
  );
  NOR _179_ (
    .A(_043_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _180_ (
    .A(_044_),
    .B(_046_),
    .Y(_048_)
  );
  NAND _181_ (
    .A(_022_),
    .B(_023_),
    .Y(_049_)
  );
  NOR _182_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _183_ (
    .A(_025_),
    .B(_027_),
    .Y(_051_)
  );
  NAND _184_ (
    .A(_009_),
    .B(_034_),
    .Y(_052_)
  );
  NAND _185_ (
    .A(_018_),
    .B(_033_),
    .Y(_053_)
  );
  NOR _186_ (
    .A(_038_),
    .B(_052_),
    .Y(_054_)
  );
  NOR _187_ (
    .A(_038_),
    .B(_053_),
    .Y(_055_)
  );
  NOT _188_ (
    .A(_055_),
    .Y(_056_)
  );
  NOR _189_ (
    .A(_054_),
    .B(_055_),
    .Y(_057_)
  );
  NOR _190_ (
    .A(_022_),
    .B(_005_),
    .Y(_058_)
  );
  NOT _191_ (
    .A(_058_),
    .Y(_059_)
  );
  NOR _192_ (
    .A(_047_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _193_ (
    .A(_051_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _194_ (
    .A(_057_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _195_ (
    .A(_050_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _196_ (
    .A(_021_),
    .B(_063_),
    .Y(_014_)
  );
  NAND _197_ (
    .A(_046_),
    .B(_058_),
    .Y(_064_)
  );
  NAND _198_ (
    .A(_037_),
    .B(_053_),
    .Y(_065_)
  );
  NAND _199_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _200_ (
    .A(_010_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _201_ (
    .A(_003_),
    .B(_026_),
    .Y(_068_)
  );
  NAND _202_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _203_ (
    .A(_046_),
    .B(_059_),
    .Y(_070_)
  );
  NAND _204_ (
    .A(_045_),
    .B(_058_),
    .Y(_071_)
  );
  NOR _205_ (
    .A(_055_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _206_ (
    .A(_056_),
    .B(_071_),
    .Y(_073_)
  );
  NOR _207_ (
    .A(_010_),
    .B(_072_),
    .Y(_074_)
  );
  NAND _208_ (
    .A(_017_),
    .B(_073_),
    .Y(_075_)
  );
  NOR _209_ (
    .A(_010_),
    .B(_043_),
    .Y(_076_)
  );
  NAND _210_ (
    .A(_010_),
    .B(_043_),
    .Y(_077_)
  );
  NOR _211_ (
    .A(_049_),
    .B(_076_),
    .Y(_078_)
  );
  NAND _212_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _213_ (
    .A(_075_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _214_ (
    .A(_069_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _215_ (
    .A(_021_),
    .B(_081_),
    .Y(_015_)
  );
  NOR _216_ (
    .A(_049_),
    .B(_077_),
    .Y(_082_)
  );
  NOR _217_ (
    .A(_074_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _218_ (
    .A(_021_),
    .B(_083_),
    .Y(_016_)
  );
  (* src = "counter_4_bits.v:36.5-77.12" *)
  DFF _219_ (
    .C(CLK),
    .D(_088_),
    .Q(Q_temp[0])
  );
  (* src = "counter_4_bits.v:36.5-77.12" *)
  DFF _220_ (
    .C(CLK),
    .D(_090_),
    .Q(Q_temp[1])
  );
  (* src = "counter_4_bits.v:36.5-77.12" *)
  DFF _221_ (
    .C(CLK),
    .D(_092_),
    .Q(Q_temp[2])
  );
  (* src = "counter_4_bits.v:36.5-77.12" *)
  DFF _222_ (
    .C(CLK),
    .D(_094_),
    .Q(Q_temp[3])
  );
  (* src = "counter_4_bits.v:36.5-77.12" *)
  DFF _223_ (
    .C(CLK),
    .D(_096_),
    .Q(RCO)
  );
  assign _100_[1] = _099_[1];
  assign _101_[1] = _099_[1];
  assign { _125_[31:4], _125_[0] } = { 28'h0000000, Q_temp[0] };
  assign _126_[31:1] = { 28'h0000000, Q_temp[3:1] };
  assign { _127_[31:4], _127_[0] } = { 27'h0000000, _125_[3], _126_[0] };
  assign _128_[2:0] = 3'h7;
  assign _129_[0] = _126_[0];
  assign _132_[0] = Q_temp[0];
  assign _133_[0] = _126_[0];
  assign _135_[1:0] = { Q_temp[1], 1'h1 };
  assign _138_[30:0] = { _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _138_[31], _133_[3:1], _126_[0] };
  assign { _139_[30:3], _139_[1:0] } = { _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _139_[31], _125_[1], Q_temp[0] };
  assign { _140_[30:4], _140_[1:0] } = { _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _140_[31], _127_[1], _126_[0] };
  assign Q = Q_temp;
  assign _011_ = RCO;
  assign _010_ = Q_temp[3];
  assign _009_ = Q_temp[2];
  assign _008_ = Q_temp[1];
  assign _007_ = Q_temp[0];
  assign _004_ = ENB;
  assign _088_ = _012_;
  assign _090_ = _013_;
  assign _092_ = _014_;
  assign _094_ = _015_;
  assign _096_ = _016_;
  assign _006_ = MODO[1];
  assign _005_ = MODO[0];
  assign _000_ = D[0];
  assign _001_ = D[1];
  assign _002_ = D[2];
  assign _003_ = D[3];
endmodule
